### PR TITLE
Add PyMCon logos

### PR DESCRIPTION
**Pull request by purna135**
Include PyMCon 2022 logos and presentation template

### CODE REVIEW

**Comment by purna135** [comment]
@reshamas, @cuchoi 
In response to the discussion, https://github.com/pymc-devs/pymcon_2022_website/issues/14 I created this PR; please take a look.

**Comment by OriolAbril** [comment]
Do we only have png files of the logos?

I would also add a readme file with some background on each file and their intended use, the colors in hex so it is easy to copy paste them if we want to use them. The pdf only has logos in them, no explanation or text.

**Comment by purna135** [comment]
I only have png files and a pdf from Slack; perhaps @cuchoi can help more with this.

**Comment by reshamas** [comment]
@OriolAbril 
I have a suggestion that we merge in this PR, so the logos can be available.

I have opened this issue:  
https://github.com/pymc-devs/brand/issues/16

Setting up the branding guide for PyMCon can take 2-4 hours, since there are so many logos.

**Comment by reshamas** [comment]
[@rowangayleschaefer](https://github.com/rowangayleschaefer) may be able to take this issue.

**Pull request merged**
