### PR TITLE
Added PyTensor logos

### PR DESCRIPTION
**Pull request by fonnesbeck**
Included important formats in README.

### CODE REVIEW

**Comment by reshamas** [comment]
@fonnesbeck 
How about we: 
1: create a folder for "pytensor":  `pymc-devs/brand/pytensor`
2: add pytensor logos in there, as we did for "pymcon"  `pymc-devs/brand/pymcon`

**Comment by fonnesbeck** [comment]
@reshamas Not opposed to that, though we should then be consistent and do the same for PyMC. Was thinking here that software logos can go in `logos` and events and other non-software branding would get their own folders.

**Comment by reshamas** [comment]
> @reshamas Not opposed to that, though we should then be consistent and do the same for PyMC. Was thinking here that software logos can go in `logos` and events and other non-software branding would get their own folders.

I'll submit a PR and put the "pymc" logos and README in its own folder.  I hadn't anticipated more branding in this repo at the time I set it up initially.  

I prefer that over a separate sub-folders.  Of course, happy to revisit that in a couple of years if the number of logos folders need to be streamlined.

Also, I will update the main README.md in this repo to link to the 3 logo folders.

**Comment by fonnesbeck** [comment]
@reshamas Want me to merge this, or submit a new PR to your reorganized repo?

**Comment by reshamas** [comment]
@fonnesbeck go ahead and merge this in. thanks.

**Pull request merged**
